//! Yale Bright Star Catalogue (BSC5) → `data/stars/bsc5.ron`.
//!
//! Source: VizieR V/50 `catalog.gz` (fixed-width ASCII, byte layout in its ReadMe).
//! Output: `(stars: [(ra: …, dec: …, vmag: …, bv: …), ...])`, J2000 equatorial, angles
//! in radians.
//! Entries without a J2000 position or a V magnitude (the 14 non-stellar objects
//! removed from the catalogue) are skipped. A missing B−V becomes 0.6.

use std::fmt::Write as _;
use std::io::Read;
use std::path::Path;

use crate::source::fetch;

const BSC5_URL: &str = "https://cdsarc.cds.unistra.fr/ftp/V/50/catalog.gz";
const DEFAULT_BV: f32 = 0.6;

#[derive(Debug, PartialEq)]
pub struct Star {
    pub ra: f64,
    pub dec: f64,
    pub vmag: f32,
    pub bv: f32,
}

/// 1-based inclusive byte columns, as in the ReadMe; `None` if blank or past the end.
fn field(line: &str, from: usize, to: usize) -> Option<&str> {
    let s = line.get(from - 1..to.min(line.len()))?.trim();
    (!s.is_empty()).then_some(s)
}

fn num<T: std::str::FromStr>(line: &str, from: usize, to: usize) -> Option<T> {
    field(line, from, to).map(|s| s.parse().unwrap_or_else(|_| panic!("bad number {s:?} in {line:?}")))
}

/// Parses one catalogue record; `None` for entries without a position or magnitude.
pub fn parse_line(line: &str) -> Option<Star> {
    let rah: f64 = num(line, 76, 77)?;
    let ram: f64 = num(line, 78, 79)?;
    let ras: f64 = num(line, 80, 83)?;
    let sign = if field(line, 84, 84)? == "-" { -1.0 } else { 1.0 };
    let ded: f64 = num(line, 85, 86)?;
    let dem: f64 = num(line, 87, 88)?;
    let des: f64 = num(line, 89, 90)?;
    let vmag: f32 = num(line, 103, 107)?;
    let bv: f32 = num(line, 110, 114).unwrap_or(DEFAULT_BV);
    let ra_hours = rah + ram / 60.0 + ras / 3600.0;
    let dec_deg = sign * (ded + dem / 60.0 + des / 3600.0);
    Some(Star { ra: (ra_hours * 15.0).to_radians(), dec: dec_deg.to_radians(), vmag, bv })
}

pub fn to_ron(stars: &[Star]) -> String {
    let mut s = String::from(
        "// Yale Bright Star Catalogue, 5th revised ed. (Hoffleit & Warren 1991; VizieR V/50).\n\
         // Generated by `cargo run -p asset-tool --release -- stars`. Do not edit.\n\
         // ra, dec: J2000 equatorial, radians. vmag: Johnson V. bv: B-V (0.6 where missing).\n\
         (stars: [\n",
    );
    for st in stars {
        // 7 decimals in radians is 0.02″, finer than the catalogue's 1″ precision.
        writeln!(s, "(ra:{:.7},dec:{:.7},vmag:{:.2},bv:{:.2}),", st.ra, st.dec, st.vmag, st.bv).expect("format star");
    }
    s.push_str("])\n");
    s
}

pub fn run() {
    println!("Stars (BSC5)");
    let gz = fetch(BSC5_URL, "bsc5_catalog.gz");
    let mut text = String::new();
    flate2::read::GzDecoder::new(std::fs::File::open(&gz).expect("open catalog.gz"))
        .read_to_string(&mut text)
        .expect("gunzip catalog");
    let lines: Vec<&str> = text.lines().collect();
    let stars: Vec<Star> = lines.iter().filter_map(|l| parse_line(l)).collect();
    println!("  {} records, {} stars with positions", lines.len(), stars.len());
    let dir = Path::new("data/stars");
    std::fs::create_dir_all(dir).expect("create data/stars");
    let path = dir.join("bsc5.ron");
    std::fs::write(&path, to_ron(&stars)).expect("write bsc5.ron");
    let bytes = std::fs::metadata(&path).expect("stat").len();
    println!("  wrote {} ({:.0} kB)", path.display(), bytes as f64 / 1e3);
}

#[cfg(test)]
mod tests {
    use super::*;

    // HR 2491 (Sirius) and HR 92 (a removed non-stellar entry) from catalog.gz.
    const SIRIUS: &str = "2491  9Alp CMaBD-16 1591  48915151881 257I   5423           064044.6-163444064508.9-164258227.22-08.88-1.46   0.00 -0.05 -0.03   A1Vm               -0.553-1.205 +.375-008SBO    13 10.3  11.2AB   4*";
    const NOVA: &str = "  92 NOVA 1572                                     B Cas                                                                                                                                            *";

    #[test]
    fn parses_sirius() {
        let s = parse_line(SIRIUS).expect("Sirius has a position");
        let ra_deg = s.ra.to_degrees();
        let dec_deg = s.dec.to_degrees();
        // 06h45m08.9s −16°42′58″ (J2000).
        assert!((ra_deg - (6.0 + 45.0 / 60.0 + 8.9 / 3600.0) * 15.0).abs() < 1e-9, "{ra_deg}");
        assert!((dec_deg + (16.0 + 42.0 / 60.0 + 58.0 / 3600.0)).abs() < 1e-9, "{dec_deg}");
        assert_eq!(s.vmag, -1.46);
        assert_eq!(s.bv, 0.0);
    }

    #[test]
    fn skips_entries_without_position() {
        assert_eq!(parse_line(NOVA), None);
    }

    #[derive(serde::Deserialize)]
    struct S {
        ra: f64,
        dec: f64,
        vmag: f32,
        bv: f32,
    }
    #[derive(serde::Deserialize)]
    struct Catalog {
        stars: Vec<S>,
    }

    #[test]
    fn committed_catalogue_parses() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../data/stars/bsc5.ron");
        let cat: Catalog = ron::from_str(&std::fs::read_to_string(path).expect("read bsc5.ron")).expect("valid RON");
        assert_eq!(cat.stars.len(), 9096);
        assert!(cat
            .stars
            .iter()
            .all(|s| (0.0..std::f64::consts::TAU).contains(&s.ra) && s.dec.abs() <= std::f64::consts::FRAC_PI_2));
        let brightest = cat.stars.iter().min_by(|a, b| a.vmag.total_cmp(&b.vmag)).unwrap();
        assert_eq!((brightest.vmag, brightest.bv), (-1.46, 0.0)); // Sirius
    }

    #[test]
    fn ron_output_deserializes() {
        let star = parse_line(SIRIUS).unwrap();
        let cat: Catalog = ron::from_str(&to_ron(&[star])).expect("valid RON");
        assert_eq!(cat.stars.len(), 1);
        let s = &cat.stars[0];
        assert!((s.ra - 1.767_793_1).abs() < 1e-6 && (s.dec + 0.291_751_2).abs() < 1e-6, "{} {}", s.ra, s.dec);
        assert_eq!((s.vmag, s.bv), (-1.46, 0.0));
    }

    #[test]
    fn missing_bv_defaults() {
        let mut line = SIRIUS.to_string();
        line.replace_range(109..114, "     ");
        assert_eq!(parse_line(&line).unwrap().bv, DEFAULT_BV);
    }
}
